### ISSUE TITLE
Allow Re-Run MUXP

### ISSUE THREAD

**Issue by nofaceinbook** [nofaceinbook/muxp#15]
After MUXP mesh update processing finishes, the button to update mesh is still not visible. However to make MUXP ready for further processing varialbes would need to be reset to the baseline.

**Comment by marangonico** [comment]
@nofaceinbook 
I think that decoupling the GUI from the muxp functionality, could be propedeutic in order to solve this problem and also for a real command line only version.

**Comment by marangonico** [comment]
Resetting the baseline would probably be translated in:
`self.muxp = MUXP()`
