### ISSUE TITLE
Reading coordinates from earth.wed.xml

### ISSUE THREAD

**Issue by marangonico** [nofaceinbook/muxp#21]
After starting to work with muxp, I've found natural to use polygons in WED, in order to extract coords and give them a role (cut_polygon, update_raster_elevation, etc).

I've defined a MUXP group, that won't be exported in the final distro, and I'm using polygons (their type is ininfluent) for every command, except for the cut_spline_segment, for which I'm using a Line.

It would be nice to implement a function for extracting these coords and create a command inside the .muxp file.

Without going so far, just copying to the clipboard the coordinates of a particular object, could be a very handy tool.

![muxp_wed](https://user-images.githubusercontent.com/3797790/83964767-79893600-a8af-11ea-9585-932ff7c8e5ca.PNG)

**Comment by nofaceinbook** [comment]
Yes, this is on my todo list. With my tool "bflat" I did this already based based on boundary polygons which appear nicely in apt.dat to be used. Did not think of using draped polygons. Do you have examples for me (the files). Would you reccomend to use then the .pol file?

**Comment by nofaceinbook** [comment]
Fixed with v0.2.7
