### ISSUE TITLE
Automated build process

### ISSUE THREAD

**Issue by marangonico** [nofaceinbook/muxp#22]
For the development phase it would be much more easier to drive the build process using the command line and skip all the interactions forced by the GUI.
In addition a sort of makefile (in YAML format) could be defined.

**Comment by nofaceinbook** [comment]
Yes. This works now with the newest version I uploaded yesterday via muxp.config. There you can now define the source dsf pack and the conflict strategy. So you will not need to interact with GUIs. The .muxp file to be changed is accepted as first argument.

**Comment by nofaceinbook** [comment]
If you agree I would close the issue?

**Comment by marangonico** [comment]
I cannot find any reference in the code about the source dsf pack and the conflict strategy.
Other than this, the muxp.config seems a global configuration, while these 2 parameters (source dsf pack and the conflict strategy) are more related to a specific scenery.
What if I'm working on two sceneries? I think that a dedicated makefile should do the trick.
You could have more than one makefile, each referencing a different source dsf, for testing different usage cases.

**Comment by nofaceinbook** [comment]
Yes/no, the values self.dsf_sceneryPack and  self.conflictStrategy are set via the muxp.config at the beginning. So they are defined global but then used for your current muxp-processing.
This works even works for several sceneries, as long as you develop them with the same base mash (e.g. default, HDmesh,...). The sceneryPack is not a specific .dsf it is the folder from which the correct .dsf is selected depending on your tile.

For the case that you want select a specific source for a muxp file I plan to include also a source definition inside the .muxp file.

But I will not support make-files. This is something I really hated when programming in C  ;-)

**Comment by marangonico** [comment]
Sorry, I wasn't looking the correct version.
I've added "dsfSourcePack" and "conflictStrategy" keys to muxp.config and it works as expected.
Thank you.
