### ISSUE TITLE
"id" variable should be avoided

### ISSUE THREAD

**Issue by marangonico** [nofaceinbook/muxp#27]
id() is an [inbuilt function](https://docs.python.org/3/library/functions.html#id) in Python and as such should be avoided.

i.e. In the muxp_file.areaIntersectionInProps() function, "id" could probably be defined as "area_id".

**Comment by nofaceinbook** [comment]
Solved with Commit: https://github.com/nofaceinbook/muxp/commit/e93f9e11c3db13db34f8da6761c679b7df8d1d32
