### ISSUE TITLE
too strict assumptions for setting "xpfolder: [INSIDE]"

### ISSUE THREAD

**Issue by marangonico** [nofaceinbook/muxp#28]
The settings "xpfolder: [INSIDE]" checks for a folder named "X-Plane 11".
This assumption is too much restrictive, since there could be more than one X-Plane installation present.
I suggest to check a couple of elements, in order to detect if we are inside a valid X-Plane folder.
Items to check could be (in no particular order):
* file "X-Plane.exe" is present
* "Custom Scenery\scenery_packs.ini" is present

**Comment by marangonico** [comment]
This log is the result  of launching muxp.exe.
It fails silently to read the muxp.config, then if the user save the config, it overwrites the original muxp.config.

> muxp-INFO: Started muxp Version: 0.2.0 exp
> muxp.xplnedsf2-INFO: Class XPLNEDSF initialized.
> muxp-INFO: GUI is set up.
> muxp-INFO: Searching Config File: C:\X-Plane-11\Custom Scenery\IT-RAZZO Casera Razzo Sources\muxp.config
> muxp.muxp_file-INFO: Reading muxp File: C:\X-Plane-11\Custom Scenery\IT-RAZZO Casera Razzo Sources\muxp.config
> muxp.muxp_file-INFO: Read key: muxpconfigversion assigned to: 1 and indent: 0
> muxp.muxp_file-INFO: Read key: xpfolder assigned to: [INSIDE] and indent: 0
> muxp.muxp_file-INFO: Read key: muxpfolder assigned to: [THIS_FOLDER] and indent: 0
> muxp.muxp_file-INFO: Read key: kmlExport assigned to: 0 and indent: 0
> muxp.muxp_file-INFO: Read key: dsfSourcePack assigned to: Global Scenery/X-Plane 11 Global Scenery and indent: 0
> muxp.muxp_file-INFO: Read key: conflictStrategey assigned to: IGNORE and indent: 0
> muxp.muxp_file-INFO: Read key: activatePack assigned to: 0 and indent: 0
> muxp-INFO:    Config read: {'commands': [], 'muxpconfigversion': '1', 'xpfolder': '[INSIDE]', 'muxpfolder': '[THIS_FOLDER]', 'kmlExport': '0', 'dsfSourcePack': 'Global Scenery/X-Plane 11 Global Scenery', 'conflictStrategey': 'IGNORE', 'activatePack': '0'}
> muxp-ERROR: Not inside X-Plane folder as stated in config file. X-Plane Folder not set! Current folder is: C:\X-Plane-11\Custom Scenery\IT-RAZZO Casera Razzo Sources
>

**Comment by nofaceinbook** [comment]
Yes, could be changed. But  as it is, it would support several X-Plane 11 installations. It is unclear whether muxp will work correctly for other X-Plane versions and for future versions it would also not be sure, wether they have X-Plane.exe or scenery_packs.ini.

**Comment by marangonico** [comment]
When I refer to more than X-Plane installation, I mean more than one X-Plane 11.
And since the name can be changed (in my case is different), it is probably a weak check.

**Comment by nofaceinbook** [comment]
Yes. Understood. Thought, that the name for X-Plane root folder is fixed. So will try checks as you mentioned.

**Comment by nofaceinbook** [comment]
Should work now. Would be great if you @marangonico could check...

**Comment by marangonico** [comment]
Will try and report back.

**Comment by marangonico** [comment]
Tried and it works, but I'd check that both conditions are satisfied.

**Comment by nofaceinbook** [comment]
@marangonico: can we close this issue?

**Comment by marangonico** [comment]
As I said, I'd check both conditions, not just one. 
Other than that, you can close it.
