### ISSUE TITLE
Silently failing when loading muxp.config, could lead to overwriting the original config file.

### ISSUE THREAD

**Issue by marangonico** [nofaceinbook/muxp#29]
This log is the result of launching muxp.exe.
It fails silently to read the muxp.config, then if the user save the config, it overwrites the original muxp.config.

muxp-INFO: Started muxp Version: 0.2.0 exp
muxp.xplnedsf2-INFO: Class XPLNEDSF initialized.
muxp-INFO: GUI is set up.
muxp-INFO: Searching Config File: C:\X-Plane-11\Custom Scenery\IT-RAZZO Casera Razzo Sources\muxp.config
muxp.muxp_file-INFO: Reading muxp File: C:\X-Plane-11\Custom Scenery\IT-RAZZO Casera Razzo Sources\muxp.config
muxp.muxp_file-INFO: Read key: muxpconfigversion assigned to: 1 and indent: 0
muxp.muxp_file-INFO: Read key: xpfolder assigned to: [INSIDE] and indent: 0
muxp.muxp_file-INFO: Read key: muxpfolder assigned to: [THIS_FOLDER] and indent: 0
muxp.muxp_file-INFO: Read key: kmlExport assigned to: 0 and indent: 0
muxp.muxp_file-INFO: Read key: dsfSourcePack assigned to: Global Scenery/X-Plane 11 Global Scenery and indent: 0
muxp.muxp_file-INFO: Read key: conflictStrategey assigned to: IGNORE and indent: 0
muxp.muxp_file-INFO: Read key: activatePack assigned to: 0 and indent: 0
muxp-INFO: Config read: {'commands': [], 'muxpconfigversion': '1', 'xpfolder': '[INSIDE]', 'muxpfolder': '[THIS_FOLDER]', 'kmlExport': '0', 'dsfSourcePack': 'Global Scenery/X-Plane 11 Global Scenery', 'conflictStrategey': 'IGNORE', 'activatePack': '0'}
muxp-ERROR: Not inside X-Plane folder as stated in config file. X-Plane Folder not set! Current folder is: C:\X-Plane-11\Custom Scenery\IT-RAZZO Casera Razzo Sources

**Comment by nofaceinbook** [comment]
Thanks for reporting. This. Function fails because X-Plane folder is named "X-Plane-11" instead "X-Plane 11". Okay. Didn't know, that it is allowed to have different naming schemes for the root X-Plane folder. So we have to follow your suggestions from your previous issue.

**Comment by nofaceinbook** [comment]
Will be solved with my todo: Before displaying config to be adapted, always read current muxp.config from file to be sure that the values of file are shown.

**Comment by nofaceinbook** [comment]
Solved. Now the muxp.config is always read before it will be changed. So only values changed by intent will be overwritten.
