### ISSUE TITLE
Feature request: mesh copy

### ISSUE THREAD

**Issue by Rodeo314** [nofaceinbook/muxp#47]
It's not 100% clear to me yet whether it's implemented, but here goes.

Some scenery developers release scenery packs with a custom mesh, but *without* an Ortho4XP patch. Or, one could have sourced ortho from a third party and not have access to all the resources to re-build the tile from scratch.

In both instances, it would be useful to be able to simply "copy" a whole tile's mesh: take the custom mesh tile as input and use an existing ortho tile as output, i.e. replacing the latter's mesh with that of the input, without having to use Ortho4XP. Would such a thing be possible?

**Comment by nofaceinbook** [comment]
Main parts for your requests are implemented. In case your scenery pack airport makes use of ortho photos then it can be directly used. The limitation for the moment is that only physical mesh can be copied and only physical mesh of one terrain type can be inserted. In case a draped polygon with ortho photo will be placed on top the limitation to one terrain type does not hurt.

Unfortunately this is not really documented in the manual:
"extract_mesh_to_file": ["coordinates"], --> extracts mesh inside polygon to a .obj file to be eg. imported in blender (only physical mesh, no overlays! and no texture exported)
"insert_mesh_from_file": ["coordinates", "terrain"], --> imports mesh from .obj file (only elevation mesh that will be set to the defined simple terrain (no s/t coordinates))
In addtion the attribute "name: filename" includes the name of the file to be exported imported.

You could try if this fits your needs for the moment. Let me know in case you need some help.
