### ISSUE TITLE
Sample files not included in download

### ISSUE THREAD

**Issue by Colins2** [nofaceinbook/muxp#64]
I downloaded the latest version but there are no sample files included.
I already have the older ones from previous downloads but I can't seem to get the new ones.

**Comment by nofaceinbook** [comment]
Hi Colins2, I just removed the samples from the Source Code. But they are still as own Zip in the release or directly in a folder next to the code:
https://github.com/nofaceinbook/muxp/tree/master/MUXP-Sample-Files

**Comment by Colins2** [comment]
Ah, I see now thanks. It isn't immediately obvious how to download. As you can see, I'm not a very experienced Git user :-)
