### ISSUE TITLE
Extracting meshes

### ISSUE THREAD

**Issue by Colins2** [nofaceinbook/muxp#66]
I find that the extract mesh command doesn't do anything when run by itself.
To explain:
I have a muxp file for an airstrip and have run it through muxp to produce the overall area with limits of 100m.
I also have a more dense area with 25m edge limits covering where the runway will be and some surrounding buildings.
This all works fine and produces what I want, as seen in GE.
I then wanted to export my modified dense area as a Blender object so I just commented out the previous instructions and substituted an extract_mesh_to_file for the dense polygon thinking that muxp would get the poly info from the modified dsf file.
However, this did not happen, I got an almost empty .obj file with no point data.

When I ran the original .muxp file on the original .dsf file with the extract instruction added after the limit commands, it all worked perfectly. Is this supposed to work like this?
Following on from that, how do I use the insert_mesh command? I would imagine that I need only the header info and then the import command.
How does muxp find the right .obj file to import or does it have to be the only .obj file in the folder where the .muxp file is?
I haven't modified the .obj file yet and so haven't tested anything.

Colin

**Comment by nofaceinbook** [comment]
Well, did you change or better remove the source_dsf key from the MUXP file? If not and "source_dsf: DEFAULT" ist set, the export will show just the few big triangles of the default mesh. If this key is removed, MUXP will ask you from which mesh you would like to extract the mesh. Here you can select your updated mesh.

For inserting mesh, muxp takes either the default name of the .obj file that is also used when writing the .obj file. But both, when exporting and when writing you can use the name key like "name: test.obj" inside the export/import command. File name is always relative to folder where the muxp file is stored.

Make sure to use the newest version of muxp in order that import/export works correct. 
I also recommend to have a look in the new version of the manual where the commands and their options are explained in detail.
I also recommend to read the following tutorial for importing/exporting mesh: https://forums.x-plane.org/index.php?/files/file/69631-updating-x-plane-mesh-with-muxp-and-blender/

**Comment by Colins2** [comment]
Thanks for the info. I now have the latest manual and everything is explained in much greater detail.
