### ISSUE TITLE
MUXP and macOS Sonoma

### ISSUE THREAD

**Issue by MortyMars** [nofaceinbook/muxp#73]
Hello,

I'm a fan of your excellent MUXP tool on macOS, and I've just tried to relaunch it after not using it for a while.
I'm now running macOS Sonoma and when I try to run the python script I get the following error message:

"Traceback (most recent call last):
  File "/Applications/MUXP12/muxp.py", line 31, in <module>
    from wed_conv import MUXP
  File "/Applications/MUXP12/wed_conv.py", line 9, in <module>
    import yaml
ModuleNotFoundError: No module named 'yaml' "

and when I try to install 'yaml' I get these :

"ERROR: Could not find a version that satisfies the requirement yaml (from versions: none)
ERROR: No matching distribution found for yaml " 

Is there a workaround?

Thanks for your help.

**Comment by nofaceinbook** [comment]
Hi @MortyMars,
thanks for using X-Plane. As you might have read I'm stoppen development if X-Plane year ago. I assume your issue could be fixed by setting the required version of yaml package to the one installed.

**Comment by nofaceinbook** [comment]
The package you need is PyYaml and the version is stated in requirement.txt in the code files.There the version is set. You could either install the dedicated version or change the version to the one you have installed.

**Comment by MortyMars** [comment]
Thank you @nofaceinbook for your quick reply even though you're no longer working on the project (which I didn't realise, sorry).

I followed your instructions and installed version 6.0.1 of PyYaml.
I've included this information in the 'requirement.txt'.
And now my macOS Sonoma MUXP is working like it did on day one: it's so cool.

Thanks again!
Best regards

**Comment by nofaceinbook** [comment]
Great. Happy to hear that it works 😀
